apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: dev-cluster
  labels:
    app: demo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-container
          image: gcr.io/project-curiosity-428718/demo-app-image:latest
          ports:
            - containerPort: 8080