apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: dev-cluster
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080