apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: dev-cluster
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: gcr-key
              mountPath: /var/secrets/google
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: gcr-key
          secret:
            secretName: gcr-json-key
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
