apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: dev-cluster
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0  # Run as root
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: jenkins
          image: gcr.io/project-curiosity-428718/custom-jenkins:latest
          ports:
            - containerPort: 8080
            - containerPort: 50000
          securityContext:
            privileged: true  # Allow privileged mode
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: gcr-key
              mountPath: /var/secrets/google
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: gcr-key
          secret:
            secretName: gcr-json-key
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
